name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Harbor Registry
      uses: docker/login-action@v2
      with:
        registry: harbor.rackspace.koski.co
        username: ${{ secrets.HARBOR_USERNAME }}
        password: ${{ secrets.HARBOR_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: harbor.rackspace.koski.co/library/ray-worker:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max